global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: quickwit
    metrics_path: /metrics
    static_configs:
      - targets:
          - benchmarks-runner:7280
  - job_name: benchmarks runner
    metrics_path: /metrics
    static_configs:
      - targets:
          - benchmarks-runner:9100
  - job_name: benchmarks monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
          - node-exporter:9100
