global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets:
          - loki:3100
  - job_name: quickwit
    metrics_path: /metrics
    static_configs:
      - targets:
          - quickwit:7280
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets:
          - node-exporter:9100
          - du-exporter:9995
  - job_name: "cadvisor"
    scrape_interval: 30s
    metric_relabel_configs:
     - action: labeldrop
       regex: "container_label_.*"
    static_configs:
      - targets:
          - cadvisor:8080
