{
 "title": "Quickwit Benchmarks",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "engine",
    "label": "Search Engine",
    "query": "SELECT DISTINCT engine FROM benchmark_sample_results GROUP BY engine;"
   },
   {
    "name": "benchmark",
    "label": "Benchmark",
    "query": "SELECT DISTINCT benchmark_label FROM benchmark_sample_results WHERE benchmark_label  != 'data-ingestion' GROUP BY benchmark_label "
   }
  ]
 },
 "panels": [
  {
   "title": "Indexing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    run_at,\r\n    MAX(avg_mean_latency) AS \"Mean\",\r\n    MAX(p99_9_latency) AS \"P99.9\",\r\n    MAX(p99_latency) AS \"P99\"\r\nFROM benchmark_sample_results\r\nWHERE \r\n    engine = '$engine' \r\n    AND benchmark_label = 'data-ingestion'\r\nGROUP BY run_id, run_at\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    run_at,\r\n    MAX(avg_mean_write_io_throughput) as \"Mean\",\r\n    MIN(min_write_io_throughput) as \"Min\",\r\n    MAX(max_write_io_throughput) as \"Max\"\r\nFROM benchmark_sample_results\r\nWHERE\r\n    engine = '$engine'\r\n    AND benchmark_label = 'data-ingestion'\r\nGROUP BY run_id, run_at\r\nLIMIT 50;"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "engine" },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    run_at,\r\n    MAX(avg_mean_latency) AS \"Mean\",\r\n    MAX(p99_9_latency) AS \"P99.9\",\r\n    MAX(p99_latency) AS \"P99\"\r\nFROM benchmark_sample_results\r\nWHERE \r\n    engine = '$engine' \r\n    AND benchmark_label = '$benchmark'\r\nGROUP BY run_id, run_at\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n    run_at,\r\n    (SUM(num_successful_requests) / SUM(runtime_secs)) as \"Rate\"\r\nFROM benchmark_sample_results\r\nWHERE\r\n    engine = '$engine'\r\n    AND benchmark_label = '$benchmark'\r\nGROUP BY run_id, run_at\r\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n    run_at,\r\n    SUM(num_successful_requests) as \"Succes\",\r\n    SUM(num_errors) as \"Errors\"\r\nFROM benchmark_sample_results\r\nWHERE\r\n    engine = '$engine'\r\n    AND benchmark_label = '$benchmark'\r\nGROUP BY run_id, run_at\r\nLIMIT 50;"
    }
   ]
  }
 ]
}